"use client";

import { useState } from "react";
import { useRouter } from "next/navigation";
import { UploadCloud, FileJson, AlertCircle } from "lucide-react";

export default function ImportsPage() {
  const [file, setFile] = useState<File | null>(null);
  const [error, setError] = useState<string>("");
  const [loading, setLoading] = useState(false);
  const router = useRouter();

  const handleUpload = async (e: React.FormEvent) => {
    e.preventDefault();
    if (!file) return;

    if (file.size > 5 * 1024 * 1024) {
      setError("File exceeds 5MB limit.");
      return;
    }

    setLoading(true);
    setError("");

    try {
      const text = await file.text();
      
      const res = await fetch("/api/admin/imports/validate", {
        method: "POST",
        headers: {
          "Content-Type": "application/json",
        },
        body: text,
      });

      const data = await res.json();

      if (!res.ok) {
        setError(data.error || "Validation failed");
        console.error(data.details);
        return;
      }

      // Save raw data to session storage so the preview page can use it
      sessionStorage.setItem(`import_${data.importId}`, text);
      router.push(`/admin/imports/${data.importId}/preview`);
    } catch {
      setError("An unexpected error occurred during upload.");
    } finally {
      setLoading(false);
    }
  };

  return (
    <div className="max-w-3xl mx-auto p-6">
      <h1 className="text-2xl font-bold mb-2">Import Question Bank</h1>
      <p className="text-slate-600 mb-8">
        Upload a valid v1 JSON file generated by your mock test instruction prompts.
      </p>

      <form onSubmit={handleUpload} className="space-y-6 bg-white p-8 rounded-2xl shadow-sm border border-slate-200">
        <div className="border-2 border-dashed border-slate-300 rounded-xl p-10 text-center hover:bg-slate-50 transition-colors">
          <input
            type="file"
            id="file-upload"
            accept=".json,application/json"
            className="hidden"
            onChange={(e) => {
              const f = e.target.files?.[0];
              if (f) {
                setFile(f);
                setError("");
              }
            }}
          />
          <label htmlFor="file-upload" className="cursor-pointer flex flex-col items-center">
            <UploadCloud className="h-12 w-12 text-slate-400 mb-4" />
            <span className="text-lg font-medium text-slate-700">Click to upload or drag and drop</span>
            <span className="text-sm text-slate-500 mt-1">JSON files up to 5MB</span>
          </label>
        </div>

        {file && (
          <div className="flex items-center gap-3 p-4 bg-blue-50 text-blue-900 rounded-lg border border-blue-100">
            <FileJson className="h-6 w-6 text-blue-500" />
            <div className="flex-1">
              <p className="font-medium">{file.name}</p>
              <p className="text-sm opacity-80">{(file.size / 1024).toFixed(1)} KB</p>
            </div>
          </div>
        )}

        {error && (
          <div className="flex items-start gap-3 p-4 bg-red-50 text-red-900 rounded-lg border border-red-100">
            <AlertCircle className="h-5 w-5 text-red-500 shrink-0 mt-0.5" />
            <div>
              <p className="font-medium">Validation Error</p>
              <p className="text-sm opacity-80">{error}</p>
            </div>
          </div>
        )}

        <div className="flex justify-end pt-4">
          <button
            type="submit"
            disabled={!file || loading}
            className="button-primary px-6 py-2.5 disabled:opacity-50 flex items-center gap-2"
          >
            {loading ? "Validating..." : "Validate and Preview"}
          </button>
        </div>
      </form>
    </div>
  );
}
