"use client";

import { BarChart3, BookOpenCheck, CircleDollarSign, Database, LogOut, Plus, Search, ShoppingBag } from "lucide-react";
import { useRouter } from "next/navigation";
import { FormEvent, useState } from "react";
import type { Product } from "@/data/catalog";

export function DashboardClient({ products, databaseReady }: { products: Product[]; databaseReady: boolean }) {
  const router = useRouter();
  const [open, setOpen] = useState(false);
  const [message, setMessage] = useState("");
  async function logout() { await fetch("/api/admin/logout", { method: "POST" }); router.push("/admin/login"); router.refresh(); }
  async function createProduct(event: FormEvent<HTMLFormElement>) {
    event.preventDefault(); const form = new FormData(event.currentTarget);
    const payload = { slug: form.get("slug"), exam: form.get("exam"), title: form.get("title"), description: form.get("description"), price: Number(form.get("price")), compareAtPrice: Number(form.get("compareAtPrice")), mockCount: Number(form.get("mockCount")), published: false, featured: false };
    const response = await fetch("/api/products", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(payload) });
    setMessage(response.ok ? "Product created." : (await response.json()).error ?? "Unable to create product.");
    if (response.ok) { setOpen(false); router.refresh(); }
  }
  return <main className="min-h-screen bg-[#eef1f8] py-10"><div className="page-shell">
    <div className="mb-8 flex flex-col justify-between gap-5 sm:flex-row sm:items-center"><div><p className="font-mono text-[10px] uppercase tracking-[.14em] text-blue">Operations centre</p><h1 className="mt-2 font-display text-5xl font-semibold tracking-[-.05em]">Good morning, Admin.</h1></div><div className="flex gap-2"><button onClick={() => setOpen(true)} className="button-primary bg-blue"><Plus size={15} /> Add series</button><button onClick={logout} className="icon-button bg-white" aria-label="Sign out"><LogOut size={17} /></button></div></div>
    <div className={`mb-8 flex items-center gap-3 rounded-2xl border p-4 text-xs ${databaseReady ? "border-emerald-300 bg-emerald-50 text-emerald-800" : "border-amber-300 bg-amber-50 text-amber-800"}`}><Database size={17} />{databaseReady ? "PostgreSQL is connected. Live CRUD is enabled." : "Preview mode: add DATABASE_URL to enable live CRUD."}</div>
    <div className="grid gap-4 md:grid-cols-4">{[[<CircleDollarSign key="i" />, "₹2.48L", "Gross revenue"], [<ShoppingBag key="i" />, "182", "Orders this month"], [<BookOpenCheck key="i" />, String(products.length), "Active series"], [<BarChart3 key="i" />, "68.4%", "Mock completion"]].map(([icon, value, label]) => <article key={String(label)} className="rounded-2xl border border-navy/10 bg-white p-5"><div className="text-blue">{icon}</div><strong className="mt-8 block font-display text-4xl">{value}</strong><span className="text-[11px] text-navy/45">{label}</span></article>)}</div>
    <section className="mt-6 overflow-hidden rounded-[24px] border border-navy/10 bg-white"><div className="flex flex-col justify-between gap-4 border-b border-navy/10 p-5 sm:flex-row sm:items-center"><div><h2 className="text-base font-extrabold">Test-series inventory</h2><p className="mt-1 text-[11px] text-navy/45">Manage pricing, publishing, and mock counts.</p></div><label className="flex items-center gap-2 rounded-full bg-mist px-4 py-2.5"><Search size={14} /><input className="bg-transparent text-xs outline-none" placeholder="Search inventory" /></label></div><div className="overflow-x-auto"><table className="w-full min-w-[720px] text-left text-xs"><thead className="bg-paper font-mono text-[9px] uppercase tracking-wider text-navy/45"><tr><th className="px-5 py-4">Series</th><th>Exam</th><th>Mocks</th><th>Price</th><th>Status</th><th className="pr-5 text-right">Action</th></tr></thead><tbody>{products.map(product => <tr key={product.id} className="border-t border-navy/8"><td className="px-5 py-4 font-bold">{product.title}</td><td>{product.shortName}</td><td>{product.mocks}</td><td>₹{product.price.toLocaleString("en-IN")}</td><td><span className="rounded-full bg-emerald-50 px-2.5 py-1 text-[9px] font-bold text-emerald-700">Published</span></td><td className="pr-5 text-right"><button className="font-bold text-blue">Edit</button></td></tr>)}</tbody></table></div></section>
    {message && <div className="fixed bottom-6 left-1/2 -translate-x-1/2 rounded-full bg-navy px-5 py-3 text-xs font-bold text-white shadow-xl">{typeof message === "string" ? message : "Request failed."}</div>}
    {open && <div className="fixed inset-0 z-[80] grid place-items-center bg-navy/55 p-4 backdrop-blur-sm"><form onSubmit={createProduct} className="max-h-[90vh] w-full max-w-xl overflow-y-auto rounded-[26px] bg-paper p-7"><div className="flex items-center justify-between"><h2 className="font-display text-4xl font-semibold">Add test series</h2><button type="button" onClick={() => setOpen(false)} className="icon-button">×</button></div><div className="mt-7 grid gap-4 sm:grid-cols-2"><AdminInput name="title" label="Title" /><AdminInput name="slug" label="URL slug" /><AdminInput name="exam" label="Exam name" /><AdminInput name="mockCount" label="Mock count" type="number" /><AdminInput name="price" label="Price (INR)" type="number" /><AdminInput name="compareAtPrice" label="Compare-at price" type="number" /></div><label className="mt-4 block"><span className="mb-2 block text-xs font-bold">Description</span><textarea name="description" required minLength={20} rows={4} className="w-full rounded-xl border border-navy/15 bg-white px-4 py-3 text-sm outline-none focus:border-blue" /></label><button className="button-primary mt-5 w-full bg-blue">Create draft</button></form></div>}
  </div></main>;
}

function AdminInput({ name, label, type = "text" }: { name: string; label: string; type?: string }) { return <label className="block"><span className="mb-2 block text-xs font-bold">{label}</span><input name={name} type={type} required className="w-full rounded-xl border border-navy/15 bg-white px-4 py-3 text-sm outline-none focus:border-blue" /></label>; }
